### ISSUE TITLE
pageRender

### ISSUE THREAD

**Issue by cadebward** [SachaG/Microscope#4]
On page 47, chapter 5 section 'Routing: mapping URLSs to templates', in your code for the file client/main.html, you write `{{renderPage}}` but I could only get it to work by putting `{{> renderPage}}`. 

Of course, I'm new to this, and if i'm doing something wrong, let me know.

**Comment by bobmonsour** [comment]
I'd guess that this is due to the new Blaze rendering engine which just came out a couple of weeks ago when Meteor 0.8 was released. See what the Discover Meteor guys wrote about it and you'll see that they refer to things like {{yield}} becoming {{> yield}}. Hope that helps. Here's the link: https://www.discovermeteor.com/blog/meteor-08-update-blaze

**Comment by SachaG** [comment]
It sounds like you might be using an outdated version of the book. Make sure you download the most recent one for the Blaze update :)
